export const WS_ORDERS_START = 'WS_ORDERS_START';
export const WS_ORDERS_CLOSE = 'WS_ORDERS_CLOSE';
export const WS_ORDERS_SUCCESS = 'WS_ORDERS_SUCCESS';
export const WS_ORDERS_ERROR = 'WS_ORDERS_ERROR';
export const WS_ORDERS_CLOSED = 'WS_ORDERS_CLOSED';
export const WS_GET_ORDERS = 'WS_GET_ORDERS';

export const WS_USER_ORDERS_START = 'WS_USER_ORDERS_START';
export const WS_USER_ORDERS_CLOSE = 'WS_USER_ORDERS_CLOSE';
export const WS_USER_ORDERS_SUCCESS = 'WS_USER_ORDERS_SUCCESS';
export const WS_USER_ORDERS_ERROR = 'WS_USER_ORDERS_ERROR';
export const WS_USER_ORDERS_CLOSED = 'WS_USER_ORDERS_CLOSED';
export const WS_GET_USER_ORDERS = 'WS_GET_USER_ORDERS';